[workspace]
authors = ["The Jupyter Community"]
channels = ["conda-forge"]
name = "jupyter-ai-team-compass"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "myst build --strict --html"
preview = "myst start"

[dependencies]
mystmd = ">=1.10.1,<2"
